# Generated by Django 4.1.1 on 2023-06-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nick', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moderador',
            fields=[
                ('nick', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('rol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.TextField()),
                ('nota', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pane.cliente')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pane.taller')),
            ],
        ),
    ]
